### ISSUE TITLE
Including static images with runDeck?

### ISSUE THREAD

**Issue by aaronjfisher** [slidify/interactive#4] opened 2014-07-22 15:15 UTC
Hi Ramnath,

This is amazing stuff! I have a super simple question, I hope this is an appropriate context to ask it. 

When I try to include static, pre-rendered images with `![Alt text](/path/to/img.png)` and compile the file with `slidify(filename.Rmd)`, everything works, but when I compile the same Rmd file with `runDeck()`, the images don't show up. Instead I get broken link icons. What am I missing here? Does this make sense?

Thanks for your time!

**Comment by ramnathv** [comment] 2014-07-22 15:45
Do you have a minimal reproducible example I can play with?

**Comment by aaronjfisher** [comment] 2014-07-22 18:25
Right, here's a sample project.

https://github.com/aaronjfisher/slidify_interactive_test

When I compile with `slidify('index.Rmd')` I see the google logo image in the .html file, but when I run `runDeck()` I don't see the image anymore. Does this reproduce on your end?

Thanks very much!

**Comment by mpodell** [comment] 2014-07-27 06:13
similar case:
http://mpodell.github.io/goal_deck/#3
files here: 
https://github.com/mpodell/goal_deck
tried jpg and png and neither will display on github.io but the image DOES display when running locally with runDeck() and locally in browser: browseURL("index.html")
I'm wondering now if mine is more of an issue with gh-pages. The rendered HTML looks right, but running from github-io, the image is not found. The image is in the assets/img folder but perhaps gh-pages do not look in the repo for assets? I tried adding the image as an issue and using that URL but still no joy.

if it is useful:

> sessionInfo()
> R version 3.1.0 (2014-04-10)
> Platform: x86_64-apple-darwin13.1.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] XML_3.98-1.1           slidifyLibraries_0.3.1 wc14goals_1.0          knitr_1.6  
[5] slidify_0.4.5          shinyapps_0.3.55       devtools_1.5           rCharts_0.4.5  
[9] shiny_0.10.0          

loaded via a namespace (and not attached):
 [1] bitops_1.0-6    caTools_1.17    codetools_0.2-8 digest_0.6.4    evaluate_0.5.5  formatR_0.10  
 [7] grid_3.1.0      htmltools_0.2.4 httpuv_1.3.0    httr_0.3        lattice_0.20-29 markdown_0.7  
[13] memoise_0.2.1   parallel_3.1.0  plyr_1.8.1      Rcpp_0.11.1     RCurl_1.95-4.1  RJSONIO_1.2-0.2
[19] stringr_0.6.2   tools_3.1.0     whisker_0.3-2   xtable_1.7-3    yaml_2.1.13

**Comment by ramnathv** [comment] 2014-07-27 07:11
@mpodell in your case, use `logo: pinspector2.jpg`, since slidify by default adds the `assets/img` path information.

**Comment by mpodell** [comment] 2014-07-27 07:19
thanks @ramnathv that works!

**Comment by mpodell** [comment] 2014-07-27 07:32
actually, 

```
url:
  assets: ./assets
```

works better for rendering the image on slide 3 only (and not on the title page)

**Comment by aaronjfisher** [comment] 2014-07-27 21:48
Thanks! That fixes mine too.

**Comment by ramnathv** [comment] 2014-07-28 00:40
Great! I will close this issue then :smile:

**Closed as completed by ramnathv** 2014-07-28 00:40 UTC

**Comment by meriops** [comment] 2014-08-13 13:16
I had the same issue and the above code did not solve it. I actually need to put the whole path to the picture for it to show in the slides. For example: `![APicture](./assets/img/picture.png)`
